### ISSUE TITLE
Difference with package WorldFlora

### ISSUE THREAD

**Issue by Rekyt** [rogerhyam/wfor#1]
Hi @rogerhyam 👋 
Great work on `wfor`! The package looks very useful.
I just wanted to know if you were aware that there was an "official" World Flora Online R package named `WorldFlora` available on CRAN at https://cran.r-project.org/package=WorldFlora
If yes, maybe it would be good to specify somewhere how does `wfor` differ from it and what additional features does it bring.

**Comment by rogerhyam** [comment]
Hi Rekyt,

My bad. I should have mentioned it in the README. I've added a comment and a link now.
